logging:
  level: INFO
  loggers:
    sk.fri.uniza: DEBUG

template: Hello, %s!
defaultName: Stranger

server:
  applicationConnectors:
    - type: http
      port: 8080
    - type: https
      port: 8443
      keyStorePath: dwstart.keystore
      keyStorePassword: crimson
      validateCerts: false
  adminConnectors:
    - type: http
      port: 8082